# 数据库配置
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: Oracle@1023
  dbname: survey
  charset: utf8mb4

# 服务器配置
server:
  host: 0.0.0.0
  port: 8080
  enable_https: false
  log_level: info

# 认证和授权配置
auth:
  jwt_secret: s8w6kcLR2lKs6eO4D2hwH8ZfzPfF9hNxTw2y5I6l8xDLsb8p/JFg==
  token_expiry: 24h

# SMTP 配置
smtp:
  from: "3299098756@qq.com"
  password: "ckbbgtcpwhaycjei"
  host: "smtp.qq.com"
  port: "587"
